version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: developer
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: mephi
