---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos/systemd:latest
    priveleged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["701", "703"]
verifier:
  name: testinfra
  lint:
    name: flake8
